# Generated by Django 5.1.5 on 2025-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_remove_salesnetwork_products_salesnetwork_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesnetwork",
            name="products",
            field=models.ManyToManyField(to="network.product", verbose_name="Продукты"),
        ),
    ]
